### ISSUE TITLE
Not support Laravel 10?

### ISSUE THREAD

**Issue by Abdallah-Tah** [saravanasai/laravel-hopeui-starter#5]
This is a good package for a start-up, could you please update to Laravel 10 and add a profile page?

Thank you,

**Comment by saravanasai** [comment]
@Abdallah-Tah  Yes, sure, I have planned to add that this weekend

**Comment by saravanasai** [comment]
@Abdallah-Tah I have added support to Laravel 10 & profile page thanks for creating issues 👍🏻
